media1 = 329,8
n1 = 20
s1 - 7,55

media2 = 273,7
n2 = 6
s2 = 6,26

# A) (Teste T)

H0: mi1 - mi2 = 60
H1: mi1 - mi2 < 60

v = (s1²/n1 + s2²/n2)²/[((s1²/n1)^2/(n1^-1))+((s2²/n2)^2/(n2^-1))]

T0 = media1 - media2 - Delta0 / sqrt((s1²/n1 + s2²/n2))
```{r}
T0 = (329.8 - 273.7 - 60)/sqrt(7.55^2/20+6.26^2/6)
T0

vnum = (7.55^2/20 + 6.26^2/6)^2
vden = (7.55^2/20)^2/19 + (6.26^2/6)^2/5

v = vnum/vden
v
   
pt(T0, v)
```

# B)

alpha = 3,3%
IC inferior = 96,7%

m1 - m2 >= media1 - media2 + qt(alpha, v*(sqrt(s1²/n1 + s2²/n2)))
```{r}
vnum = (7.55^2/20 + 6.26^2/6)^2
vden = (7.55^2/20)^2/19 + (6.26^2/6)^2/5

v = vnum/vden

329.8 - 273.7 + qt(0.033, v) * sqrt(7.55^2/20 + 6.26^2/6)
```

# C)

H0: sigma1²/sigma2² = 1
H1: sigma1²/sigma2² > 1

f0 = s1²/(k²*s2²)
```{r}
f0 = (7.55^2)/(6.26^2)
f0

pf(f0, 19, 5, lower.tail = FALSE)
```

*# ==================================================================================================== *

# 2)

n = 10

media1 = 30
S1 = 5

media2 = 40
s2 = 1

# A)

alpha = 0.05

H0: mi1 - mi2 = 0
H1: mi1 - mi2 > 0

T0 = 30 - 40 - 0 / sqrt(5^2/10 + 1^2/10)

vnum = (5^2/10 + 1^2/10)^2
vden = (5^2/10)^2/9 + (1^2/10)^2/9

```{r}
T0 = (30 - 40 - 0) / sqrt(5^2/10 + 1^2/10)

vnum = (5^2/10 + 1^2/10)^2
vden = ((5^2/10)^2/9) + ((1^2/10)^2/9)
v = vnum/vden

2*pt(abs(T0), v, lower=FALSE)
```

# B) (Teste F)

F0 = 5^2/1^2
u = 9
v = 9
```{r}
F0 = 5^2/1^2
u = 9
v = 9

2*pf(F0, u, v, lower=FALSE)

```
*# ==================================================================================================== *

# 3)

alpha = 0.05

media1 = 6.76
s1 = 1.97
n1 = 13

media2 = 6.25
s2 = 1.69
n2 = 16

# A)

(teste T)

```{r}
v = (1.97^2/13 + 1.69^2/16)^2/((1.97^2/13)^2/12 + (1.69^2/16)^2/15)

6.76 - 6.25 + qt(0.05/2, v) * sqrt(1.97^2/13 + 1.69^2/16)
6.76 - 6.25 + qt(1 - 0.05/2, v) * sqrt(1.97^2/13 + 1.69^2/16)
```

# B)

u = 12
n = 15

f0 = 1.97^2/1.69^2

(1.97^2/1.69^2) * qf(0.05/2, v, u)
(1.97^2/1.69^2) * qf(1 - 0.05/2, v, u)

```{r}
v = 15
u = 12

1.97^2/1.69^2 * qf(0.05/2, v, u)
1.97^2/1.69^2 * qf(1 - 0.05/2, v, u)
```

# C)

T0 = (6.76 - 6.25 - 0) / sqrt((1.97^2/13)^2/12 + (1.69^2/16)^2)

```{r}
v = (1.97^2/13 + 1.69^2/16)^2/((1.97^2/13)^2/12 + (1.69^2/16)^2/15)

T0 = (6.76 - 6.25 - 0) / sqrt(1.97^2/13 + 1.69^2/16)

pt(T0, v, lower=FALSE)

```

# D)

F0 = 1.97^2/1.69^2

```{r}
F0 = 1.97^2/1.69^2

2*pf(F0, 12, 15, lower=FALSE)
```

















